token: 'your bot token'
guild: 'id of the guild for which this config is written'
overview: 'channel name in which the embed for assigning roles via reactions is posted'
# file path for storing reaction message handlers
rm: 'rm-template.yml'
lectures:
  - name: 'name of some lecture'
    embed_title: 'title of embed in overview channel'
    role: 'name or id of role associated with this lecture'
    emoji: 'name or id of emoji associated with this lecture'
    channel: 'name or id of channel associated with this lecture'