name: Codestyle

on: [push]

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: autopep8
        run: autopep8 -r --diff --exit-code src/
      - name: pylint
        run: pylint src/
