name: Deploy

on:
  push:
    branches:
      - 56-continuous-deployment
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd physicsbot
            git pull
            docker build --build-arg=$(git rev-parse --short HEAD) -t physicsbot:master .
            docker run \
              --detach
              -v $(pwd)/role-dist.yml:/physicsbot/role-dist.yml \
              --name physicsbot
              physicsbot:master
